TabDemoMoves      .byte $ff
                  .byte $ff
                  .byte $1e
                  .byte $77
                  .byte $2d
                  .byte $97
                  .byte $4f
                  .byte $2d
                  .byte $47
                  .byte $3e
                  .byte $1b
                  .byte $4f
                  .byte $1e
                  .byte $b7
                  .byte $1d
                  .byte $27
                  .byte $4f
                  .byte $6d
                  .byte $17
                  .byte $4d
                  .byte $3b
                  .byte $4f
                  .byte $1d
                  .byte $1b
                  .byte $47
                  .byte $3b
                  .byte $4f
                  .byte $4e
                  .byte $5b
                  .byte $3e
                  .byte $5b
                  .byte $4d
                  .byte $3b
                  .byte $5f
                  .byte $3e
                  .byte $ab
                  .byte $1e
                  .byte $3b
                  .byte $1d
                  .byte $6b
                  .byte $4d
                  .byte $17
                  .byte $4f
                  .byte $3d
                  .byte $47
                  .byte $4d
                  .byte $4b
                  .byte $2e
                  .byte $27
                  .byte $3e
                  .byte $a7
                  .byte $a7
                  .byte $1d
                  .byte $47
                  .byte $1d
                  .byte $47
                  .byte $2d
                  .byte $5f
                  .byte $57
                  .byte $4e
                  .byte $57
                  .byte $6f
                  .byte $1d
                  .byte $00 ; <EndOfDemo> 
; ------------------------------------------------------------------------------------------------------------- ;
