TabGfxStore       = * - $0100                     ; first page contains in game music - all copied over to $3000
; ------------------------------------------------------------------------------------------------------------- ;
                  .byte $00 ; ........  -> $3100 = Gfx_20 - BD_TileBttrFly top left
                  .byte $3c ; ..####..
                  .byte $60 ; .##.....
                  .byte $3c ; ..####..
                  .byte $06 ; .....##.
                  .byte $06 ; .....##.
                  .byte $3c ; ..####..
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3108 = Gfx_21 - BD_TileBttrFly top right
                  .byte $63 ; .##...##
                  .byte $77 ; .###.###
                  .byte $7f ; .#######
                  .byte $6b ; .##.#.##
                  .byte $63 ; .##...##
                  .byte $63 ; .##...##
                  .byte $00 ; ........
                  
                  .byte $3f ; ..######  -> $3110 = Gfx_22 - BD_TileWallMagic top left
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $3f ; ..######  -> $3118 = Gfx_23 - BD_TileWallMagic top right
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3120 = Gfx_24 - BD_TileExplDmnd0 top left
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $0c ; ....##..
                  .byte $30 ; ..##....
                  .byte $03 ; ......##
                  
                  .byte $00 ; ........  -> $3128 = Gfx_25 - BD_TileExplDmnd0 top right
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $00 ; ........
                  .byte $c0 ; ##......
                  .byte $0c ; ....##..
                  
                  .byte $00 ; ........  -> $3130 = Gfx_26 - BD_TileExplDmnd1 top left
                  .byte $cc ; ##..##..
                  .byte $00 ; ........
                  .byte $0c ; ....##..
                  .byte $30 ; ..##....
                  .byte $00 ; ........
                  .byte $c0 ; ##......
                  .byte $00 ; ........
                  
                  .byte $c0 ; ##......  -> $3138 = Gfx_27 - BD_TileExplDmnd1 top right
                  .byte $0c ; ....##..
                  .byte $00 ; ........
                  .byte $cc ; ##..##..
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $03 ; ......##
                  .byte $00 ; ........
                  
                  .byte $01 ; .......#  -> $3140 = Gfx_28 - BD_TileExplDmnd2 top left
                  .byte $33 ; ..##..##
                  .byte $04 ; .....#..
                  .byte $0c ; ....##..
                  .byte $02 ; ......#.
                  .byte $00 ; ........
                  .byte $48 ; .#..#...
                  .byte $c0 ; ##......
                  
                  .byte $40 ; .#......  -> $3148 = Gfx_29 - BD_TileExplDmnd2 top right
                  .byte $00 ; ........
                  .byte $13 ; ...#..##
                  .byte $b0 ; #.##....
                  .byte $04 ; .....#..
                  .byte $0c ; ....##..
                  .byte $21 ; ..#....#
                  .byte $03 ; ......##
                  
                  .byte $01 ; .......#  -> $3150 = Gfx_2a - BD_TileExplDmnd3 top left
                  .byte $03 ; ......##
                  .byte $04 ; .....#..
                  .byte $0c ; ....##..
                  .byte $12 ; ...#..#.
                  .byte $30 ; ..##....
                  .byte $4b ; .#..#.##
                  .byte $d2 ; ##.#..#.
                  
                  .byte $40 ; .#......  -> $3158 = Gfx_2b - BD_TileExplDmnd3 top right
                  .byte $c0 ; ##......
                  .byte $10 ; ...#....
                  .byte $b0 ; #.##....
                  .byte $04 ; .....#..
                  .byte $cc ; ##..##..
                  .byte $61 ; .##....#
                  .byte $8b ; #...#.##
                  
                  .byte $01 ; .......#  -> $3160 = Gfx_2c - BD_TileExplDmnd4 top left
                  .byte $03 ; ......##
                  .byte $06 ; .....##.
                  .byte $0e ; ....###.
                  .byte $17 ; ...#.###
                  .byte $3b ; ..###.##
                  .byte $6d ; .##.##.#
                  .byte $fb ; #####.##
                  
                  .byte $40 ; .#......  -> $3168 = Gfx_2d - BD_TileExplDmnd4 top right
                  .byte $c0 ; ##......
                  .byte $50 ; .#.#....
                  .byte $b0 ; #.##....
                  .byte $e4 ; ###..#..
                  .byte $ac ; #.#.##..
                  .byte $7d ; .#####.#
                  .byte $e7 ; ###..###
                  
                  .byte $aa ; #.#.#.#.  -> $3170 = Gfx_2e - BD_TileXitClose top left
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $aa ; #.#.#.#.  -> $3178 = Gfx_2f - BD_TileXitClose top right
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $00 ; ........  -> $3180 = Gfx_30
                  .byte $66 ; .##..##.
                  .byte $66 ; .##..##.
                  .byte $3c ; ..####..
                  .byte $18 ; ...##...
                  .byte $18 ; ...##...
                  .byte $18 ; ...##...
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3188 = Gfx_31
                  .byte $00 ; ........ 
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $3f ; ..######  -> $3190 = Gfx_32
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $3f ; ..######  -> $3198 = Gfx_33
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $31a0 = Gfx_34
                  .byte $0c ; ....##..
                  .byte $30 ; ..##....
                  .byte $03 ; ......##
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $c0 ; ##......  -> $31a8 = Gfx_35
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $c0 ; ##......
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $31b0 = Gfx_36
                  .byte $c0 ; ##......
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $03 ; ......##
                  .byte $c0 ; ##......
                  .byte $0c ; ....##..
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $31b8 = Gfx_37
                  .byte $0c ; ....##..
                  .byte $00 ; ........
                  .byte $c3 ; ##....##
                  .byte $00 ; ........
                  .byte $0c ; ....##..
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $40 ; .#......  -> $31c0 = Gfx_38
                  .byte $c8 ; ##..#...
                  .byte $00 ; ........
                  .byte $32 ; ..##..#.
                  .byte $04 ; .....#..
                  .byte $0c ; ....##..
                  .byte $31 ; ..##...#
                  .byte $03 ; ......##
                  
                  .byte $02 ; ......#.  -> $31c8 = Gfx_39
                  .byte $03 ; ......##
                  .byte $28 ; ..#.#...
                  .byte $0c ; ....##..
                  .byte $60 ; .##.....
                  .byte $03 ; ......##
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  
                  .byte $43 ; .#....##  -> $31d0 = Gfx_3a
                  .byte $c8 ; ##..#...
                  .byte $14 ; ...#.#..
                  .byte $32 ; ..##..#.
                  .byte $07 ; .....###
                  .byte $0c ; ....##..
                  .byte $01 ; .......#
                  .byte $03 ; ......##
                  
                  .byte $16 ; ...#.##.  -> $31d8 = Gfx_3b
                  .byte $83 ; #.....##
                  .byte $38 ; ..#.#...
                  .byte $8c ; #...##..
                  .byte $20 ; ..#.....
                  .byte $70 ; .###....
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  
                  .byte $6b ; .##.#.##  -> $31e0 = Gfx_3c
                  .byte $ed ; ###.##.#
                  .byte $1b ; ...##.##
                  .byte $39 ; ..###..#
                  .byte $07 ; .....###
                  .byte $0e ; ....###.
                  .byte $01 ; .......#
                  .byte $03 ; ......##
                  
                  .byte $b6 ; #.##.##.  -> $31e8 = Gfx_3d
                  .byte $d7 ; ##.#.###
                  .byte $78 ; .####...
                  .byte $9c ; #..###..
                  .byte $e0 ; ###.....
                  .byte $70 ; .###....
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  
                  .byte $aa ; #.#.#.#.  -> $31f0 = Gfx_3e
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $aa ; #.#.#.#.  -> $31f8 = Gfx_3f
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $3f ; ..######  -> $3200 = Gfx_40 - BD_TileAmoeba top left
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $3f ; ..######  -> $3208 = Gfx_41 - BD_TileAmoeba top right
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3210 = Gfx_42
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3218 = Gfx_43
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.#...
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  
                  .byte $0f ; ....####  -> $3220 = Gfx_44 - BD_TileBldr top left
                  .byte $3b ; ..###.##
                  .byte $de ; ##.####.
                  .byte $b6 ; #.##.##.
                  .byte $a9 ; #.#.#..#
                  .byte $9a ; #..##.#.
                  .byte $a5 ; #.#..#.#
                  .byte $aa ; #.#.#.#.
                  
                  .byte $c0 ; ##......  -> $3228 = Gfx_45 - BD_TileBldr top right
                  .byte $70 ; .###....
                  .byte $fc ; ######..
                  .byte $7f ; .#######
                  .byte $bf ; #.######
                  .byte $9b ; #..##.##
                  .byte $af ; #.#.####
                  .byte $9b ; #..##.##
                  
                  .byte $04 ; .....#..  -> $3230 = Gfx_46 - BD_TileSoil top left
                  .byte $50 ; .#.#....
                  .byte $19 ; ...##..#
                  .byte $51 ; .#.#...#
                  .byte $45 ; .#...#.#
                  .byte $24 ; ..#..#..
                  .byte $96 ; #..#.##.
                  .byte $45 ; .#...#.#
                  
                  .byte $11 ; ...#...#  -> $3238 = Gfx_47 - BD_TileSoil top left
                  .byte $41 ; .#.....#
                  .byte $18 ; ...##...
                  .byte $51 ; .#.#...#
                  .byte $45 ; .#...#.#
                  .byte $64 ; .##..#..
                  .byte $85 ; #....#.#
                  .byte $58 ; .#.##...
                  
                  .byte $01 ; .......#  -> $3240 = Gfx_48 - BD_TileDmnd top left
                  .byte $03 ; ......##
                  .byte $04 ; .....#..
                  .byte $0c ; ....##..
                  .byte $10 ; ...#....
                  .byte $30 ; ..##....
                  .byte $40 ; .#......
                  .byte $c0 ; ##......
                  
                  .byte $40 ; .#......  -> $3248 = Gfx_49 - BD_TileDmnd top right
                  .byte $c0 ; ##......
                  .byte $10 ; ...#....
                  .byte $30 ; ..##....
                  .byte $04 ; .....#..
                  .byte $0c ; ....##..
                  .byte $01 ; .......#
                  .byte $03 ; ......##
                  
                  .byte $aa ; #.#.#.#.  -> $3250 = Gfx_4a - BD_TileWallSteel top left
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $aa ; #.#.#.#.  -> $3258 = Gfx_4b - BD_TileWallSteel top right
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $f0 ; ####....  -> $3260 = Gfx_4c - BD_TileRockFord top left
                  .byte $3f ; ..######
                  .byte $fb ; #####.##
                  .byte $fb ; #####.##
                  .byte $ff ; ########
                  .byte $3c ; ..####..
                  .byte $0f ; ....####
                  .byte $0a ; ....#.#.
                  
                  .byte $0f ; ....####  -> $3268 = Gfx_4d - BD_TileRockFord top right
                  .byte $fc ; ######..
                  .byte $ef ; ###.####
                  .byte $ef ; ###.####
                  .byte $ff ; ########
                  .byte $3c ; ..####..
                  .byte $30 ; ..##....
                  .byte $a0 ; #.#.....
                  
                  .byte $3f ; ..######  -> $3270 = Gfx_4e - BD_TileWallBrick top left
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $3f ; ..######  -> $3278 = Gfx_4f - BD_TileWallBrick top right
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3280 = Gfx_50
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0b ; ....#.##
                  .byte $0b ; ....#.##
                  
                  .byte $00 ; ........  -> $3288 = Gfx_51
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $03 ; ......##
                  .byte $31 ; ..##...#
                  .byte $18 ; ...##...
                  .byte $20 ; ..#.....
                  .byte $d2 ; ##.#..#.
                  
                  .byte $23 ; ..#...##  -> $3290 = Gfx_52
                  .byte $32 ; ..##..#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  
                  .byte $c8 ; ##..#...  -> $3298 = Gfx_53
                  .byte $8c ; #...##..
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $8a ; #...#.#.  -> $32a0 = Gfx_54
                  .byte $a2 ; #.#...#.
                  .byte $8a ; #...#.#.
                  .byte $a2 ; #.#...#.
                  .byte $a8 ; #.#.#...
                  .byte $2a ; ..#.#.#.
                  .byte $08 ; ....#...
                  .byte $02 ; ......#.
                  
                  .byte $a9 ; #.#.#..#  -> $32a8 = Gfx_55
                  .byte $99 ; #..##..#
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $a8 ; #.#.#...
                  .byte $a8 ; #.#.#...
                  .byte $60 ; .##.....
                  .byte $80 ; #.......
                  
                  .byte $15 ; ...#.#.#  -> $32b0 = Gfx_56
                  .byte $61 ; .##....#
                  .byte $64 ; .##..#..
                  .byte $25 ; ..#..#.#
                  .byte $44 ; .#...#..
                  .byte $50 ; .#.#....
                  .byte $46 ; .#...##.
                  .byte $10 ; ...#....
                  
                  .byte $95 ; #..#.#.#  -> $32b8 = Gfx_57
                  .byte $58 ; .#.##...
                  .byte $91 ; #..#...#
                  .byte $19 ; ...##..#
                  .byte $44 ; .#...#..
                  .byte $51 ; .#.#...#
                  .byte $10 ; ...#....
                  .byte $44 ; .#...#..
                  
                  .byte $40 ; ..##....  -> $32c0 = Gfx_58
                  .byte $c0 ; ##......
                  .byte $10 ; ...#....
                  .byte $30 ; ..##....
                  .byte $04 ; .....#..
                  .byte $0c ; ....##..
                  .byte $01 ; .......#
                  .byte $03 ; ......##
                  
                  .byte $02 ; ......#.  -> $32c8 = Gfx_59
                  .byte $03 ; ......##
                  .byte $08 ; ....#...
                  .byte $0c ; ....##..
                  .byte $20 ; ..#.....
                  .byte $30 ; ..##....
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  
                  .byte $aa ; #.#.#.#.  -> $32d0 = Gfx_5a
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $aa ; #.#.#.#.  -> $32d8 = Gfx_5b
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $5a ; .#.##.#.  -> $32e0 = Gfx_5c
                  .byte $4a ; .#..#.#.
                  .byte $0a ; ....#.#.
                  .byte $3f ; ..######
                  .byte $3c ; ..####..
                  .byte $30 ; ..##....
                  .byte $f0 ; ####....
                  .byte $00 ; ........
                  
                  .byte $a4 ; #.#..#..  -> $32e8 = Gfx_5d
                  .byte $a1 ; #.#....#
                  .byte $a4 ; #.#..#..
                  .byte $fc ; ######..
                  .byte $3c ; ..####..
                  .byte $0c ; ....##..
                  .byte $0c ; ....##..
                  .byte $0f ; ....####
                  
                  .byte $3f ; ..######  -> $32f0 = Gfx_5e
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $3f ; ..######  -> $32f8 = Gfx_5f
                  .byte $2f ; ..#.####
                  .byte $2a ; ..#.#.#.
                  .byte $00 ; ........
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $a2 ; #.#...#.
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3300 = Gfx_60 - BD_TileEmpty top left
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........     $3304
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3308 = Gfx_61 - BD_TileEmpty top right
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........     $330c
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $aa ; #.#.#.#.  -> $3310 = Gfx_62 - BD_TileXitOpen/BD_TileBirthRF0 top left
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $aa ; #.#.#.#.  -> $3318 = Gfx_63 - BD_TileXitOpen/BD_TileBirthRF0 top right
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $ff ; ########  -> $3320 = Gfx_64 - BD_TileFireFly top left
                  .byte $ef ; ###.####
                  .byte $ea ; ###.#.#.
                  .byte $c0 ; ##......
                  .byte $f3 ; ####..##
                  .byte $f3 ; ####..##
                  .byte $a3 ; #.#...##
                  .byte $03 ; ......##
                  
                  .byte $3f ; ..######  -> $3328 = Gfx_65 - BD_TileFireFly top right
                  .byte $3f ; ..######
                  .byte $3a ; ..###.#.
                  .byte $30 ; ..##....
                  .byte $ff ; ########
                  .byte $fe ; #######.
                  .byte $ae ; #.#.###.
                  .byte $0c ; ....##..
                  
                  .byte $00 ; ........  -> $3330 = Gfx_66 - BD_TileXplEmpty0/BD_TileXplEmpty4/BD_TileBirthRF1 top left
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $0c ; ....##..
                  .byte $30 ; ..##....
                  .byte $03 ; ......##
                  
                  .byte $00 ; ........  -> $3338 = Gfx_67 - BD_TileXplEmpty0/BD_TileXplEmpty4/BD_TileBirthRF1 top right
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $00 ; ........
                  .byte $c0 ; ##......
                  .byte $0c ; ....##..
                  
                  .byte $00 ; ........  -> $3340 = Gfx_68 - BD_TileXplEmpty1/BD_TileXplEmpty3/BD_TileBirthRF2 top left
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $03 ; ......##
                  .byte $34 ; ..##.#..
                  .byte $10 ; ...#....
                  .byte $31 ; ..##...#
                  
                  .byte $00 ; ........  -> $3348 = Gfx_69 - BD_TileXplEmpty1/BD_TileXplEmpty3/BD_TileBirthRF2 top right
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $10 ; ...#....
                  .byte $0c ; ....##..
                  .byte $74 ; .###.#..
                  .byte $04 ; .....#..
                  
                  .byte $00 ; ........  -> $3350 = Gfx_6a - BD_TileXplEmpty2/BD_TileBirthRF3 top left
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $03 ; ......##
                  .byte $31 ; ..##...#
                  .byte $18 ; ...##...
                  .byte $20 ; ..#.....
                  .byte $d2 ; ##.#..#.
                  
                  .byte $00 ; ........  -> $3358 = Gfx_6b - BD_TileXplEmpty2/BD_TileBirthRF3 top right
                  .byte $00 ; ........
                  .byte $cc ; ##..##..
                  .byte $20 ; ..#.....
                  .byte $1c ; ...###..
                  .byte $04 ; .....#..
                  .byte $98 ; #..##...
                  .byte $08 ; ....#...
                  
                  .byte $ff ; ########  -> $3360 = Gfx_6c
                  .byte $ef ; ###.####
                  .byte $ea ; ###.#.#.
                  .byte $c0 ; ##......
                  .byte $f3 ; ####..##
                  .byte $f3 ; ####..##
                  .byte $a3 ; #.#...##
                  .byte $03 ; ......##
                  
                  .byte $3f ; ..######  -> $3368 = Gfx_6d
                  .byte $3f ; ..######
                  .byte $3a ; ..###.#.
                  .byte $30 ; ..##....
                  .byte $ff ; ########
                  .byte $fe ; #######.
                  .byte $ae ; #.#.###.
                  .byte $0c ; ....##..
                  
                  .byte $3f ; ..######  -> $3370 = Gfx_6e
                  .byte $2f ; ..#.####
                  .byte $2e ; ..#.###.
                  .byte $0c ; ....##..
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $b2 ; #.##..#.
                  .byte $30 ; ..##....
                  
                  .byte $3f ; ..######  -> $3378 = Gfx_6f
                  .byte $2f ; ..#.####
                  .byte $2b ; ..#.#.##
                  .byte $03 ; ......##
                  .byte $f3 ; ####..##
                  .byte $f2 ; ####..#.
                  .byte $e2 ; ###...#.
                  .byte $c0 ; ##......
                  
                  .byte $00 ; ........  -> $3380 = Gfx_70
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........     $3384
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3388 = Gfx_71
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........     $338c
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $80 ; #.......  -> $3390 = Gfx_72
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  .byte $aa ; #.#.#.#.
                  
                  .byte $02 ; ......#.  -> $3398 = Gfx_73
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $7c ; .#####..  -> $33a0 = Gfx_74
                  .byte $7c ; .#####..
                  .byte $7c ; .#####..
                  .byte $7c ; .#####..
                  .byte $2f ; ..#.####
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $7c ; .#####..  -> $33a8 = Gfx_75
                  .byte $7c ; .#####..
                  .byte $7c ; .#####..
                  .byte $7c ; .#####..
                  .byte $ff ; ########
                  .byte $7c ; .#####..
                  .byte $7c ; .#####..
                  .byte $7c ; .#####..
                  
                  .byte $00 ; ........  -> $33b0 = Gfx_76
                  .byte $0c ; ....##..
                  .byte $30 ; ..##....
                  .byte $03 ; ......##
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $c0 ; ##......  -> $33b8 = Gfx_77
                  .byte $00 ; ........
                  .byte $30 ; ..##....
                  .byte $c0 ; ##......
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $33c0 = Gfx_78
                  .byte $34 ; ..##.#..
                  .byte $11 ; ...#...#
                  .byte $0d ; ....##.#
                  .byte $0c ; ....##..
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $70 ; .###....  -> $33c8 = Gfx_79
                  .byte $40 ; .#......
                  .byte $10 ; ...#....
                  .byte $4c ; .#..##..
                  .byte $c0 ; ##......
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $33d0 = Gfx_7a
                  .byte $d8 ; ##.##...
                  .byte $22 ; ..#...#.
                  .byte $06 ; .....##.
                  .byte $c4 ; ##...#..
                  .byte $03 ; ......##
                  .byte $30 ; ..##....
                  .byte $00 ; ........
                  
                  .byte $50 ; .#.#....  -> $33d8 = Gfx_7b
                  .byte $4c ; .#..##..
                  .byte $10 ; ...#....
                  .byte $44 ; .#...#..
                  .byte $4c ; .#..##..
                  .byte $c0 ; ##......
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $aa ; #.#.#.#.  -> $33e0 = Gfx_7c
                  .byte $aa ; #.#.#.#.
                  .byte $82 ; #.....#.
                  .byte $a2 ; #.#...#.
                  .byte $b2 ; #.##..#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  .byte $aa ; #.#.#.#.
                  
                  .byte $00 ; ........  -> $33e8 = Gfx_7d
                  .byte $f0 ; ####....
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $0f ; ....####
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $33f0 = Gfx_7e
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $33f8 = Gfx_7f
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  .byte $00 ; ........
                  
                  .byte $00 ; ........  -> $3400 = Gfx_80
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $2a ; ..#.#.#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3408 = Gfx_81
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $a8 ; #.#.#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  
                  .byte $00 ; ........  -> $3410 = Gfx_82
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $2a ; ..#.#.#.
                  .byte $2a ; ..#.#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3418 = Gfx_83
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $a8 ; #.#.#...
                  .byte $a8 ; #.#.#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  
                  .byte $00 ; ........  -> $3420 = Gfx_84
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $2a ; ..#.#.#.
                  .byte $2a ; ..#.#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3428 = Gfx_85
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $a8 ; #.#.#...
                  .byte $a8 ; #.#.#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  
                  .byte $00 ; ........  -> $3430 = Gfx_86
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $2a ; ..#.#.#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3438 = Gfx_87
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $a8 ; #.#.#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  
                  .byte $00 ; ........  -> $3440 = Gfx_88
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3448 = Gfx_89
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #..#....
                  .byte $a0 ; #.#.....
                  
                  .byte $00 ; ........  -> $3450 = Gfx_8a
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3458 = Gfx_8b
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  
                  .byte $00 ; ........  -> $3460 = Gfx_8c
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3468 = Gfx_8d
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  
                  .byte $00 ; ........  -> $3470 = Gfx_8e
                  .byte $08 ; ....#...
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  
                  .byte $00 ; ........  -> $3478 = Gfx_8f
                  .byte $20 ; ..#.....
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  
                  .byte $23 ; ..#...##  -> $3480 = Gfx_90
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  .byte $00 ; ........
                  
                  .byte $c8 ; ##..#...  -> $3488 = Gfx_91
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $23 ; ..#...##  -> $3490 = Gfx_92
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  .byte $00 ; ........
                  
                  .byte $c8 ; ##..#...  -> $3498 = Gfx_93
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $23 ; ..#...##  -> $34a0 = Gfx_94
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  .byte $00 ; ........
                  
                  .byte $c8 ; ##..#...  -> $34a8 = Gfx_95
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $23 ; ..#...##  -> $34b0 = Gfx_96
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  .byte $00 ; ........
                  
                  .byte $c8 ; ##..#...  -> $34b8 = Gfx_97
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $23 ; ..#...##  -> $34c0 = Gfx_98
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  
                  .byte $c8 ; ##..#...  -> $34c8 = Gfx_99
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $23 ; ..#...##  -> $34d0 = Gfx_9a
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  
                  .byte $c8 ; ##..#...  -> $34d8 = Gfx_9b
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $23 ; ..#...##  -> $34e0 = Gfx_9c
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  
                  .byte $c8 ; ##..#...  -> $34e8 = Gfx_9d
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $23 ; ..#...##  -> $34f0 = Gfx_9e
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  
                  .byte $c8 ; ##..#...  -> $34f8 = Gfx_9f
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $00 ; ........  -> $3500 = Gfx_a0
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3508 = Gfx_a1
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #..#....
                  
                  .byte $00 ; ........  -> $3510 = Gfx_a2
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3518 = Gfx_a3
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3520 = Gfx_a4
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3528 = Gfx_a5
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3530 = Gfx_a6
                  .byte $00 ; ........
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3538 = Gfx_a7
                  .byte $00 ; ........
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3540 = Gfx_a8
                  .byte $00 ; ........
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3548 = Gfx_a9
                  .byte $00 ; ........
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3550 = Gfx_aa
                  .byte $00 ; ........
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3558 = Gfx_ab
                  .byte $00 ; ........
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3560 = Gfx_ac
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ....#.#.
                  
                  .byte $00 ; ........  -> $3568 = Gfx_ad
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3570 = Gfx_ae
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $22 ; ..#...#.
                  .byte $22 ; ..#...#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3578 = Gfx_af
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $03 ; ......##  -> $3580 = Gfx_b0
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $f0 ; ####....
                  
                  .byte $c0 ; ##......  -> $3588 = Gfx_b1
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d4 ; ##.#.#..
                  .byte $03 ; ......##
                  .byte $03 ; ......##
                  .byte $00 ; ........
                  
                  .byte $03 ; ......##  -> $3590 = Gfx_b2
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $f0 ; ####....
                  
                  .byte $c0 ; ##......  -> $3598 = Gfx_b3
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d4 ; ##.#.#..
                  .byte $03 ; ......##
                  .byte $03 ; ......##
                  .byte $00 ; ........
                  
                  .byte $03 ; ......##  -> $35a0 = Gfx_b4
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  
                  .byte $c0 ; ##......  -> $35a8 = Gfx_b5
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $17 ; ...#.###
                  .byte $03 ; ......##
                  .byte $00 ; ........
                  
                  .byte $03 ; ......##  -> $35b0 = Gfx_b6
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  
                  .byte $c0 ; ##......  -> $35b8 = Gfx_b7
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $54 ; .#.#.#..
                  .byte $1c ; ...###..
                  .byte $0c ; ....##..
                  
                  .byte $03 ; ......##  -> $35c0 = Gfx_b8
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $01 ; .......#
                  .byte $01 ; .......#
                  .byte $0f ; ....####
                  
                  .byte $c0 ; ##......  -> $35c8 = Gfx_b9
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $40 ; .#......
                  .byte $70 ; .###....
                  .byte $30 ; ..##....
                  
                  .byte $03 ; ......##  -> $35d0 = Gfx_ba
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $05 ; .....#.#
                  .byte $05 ; .....#.#
                  .byte $03 ; .....#.#
                  
                  .byte $c0 ; ##......  -> $35d8 = Gfx_bb
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $40 ; .#......
                  .byte $40 ; .#......
                  .byte $c0 ; ##......
                  
                  .byte $03 ; ......##  -> $35e0 = Gfx_bc
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $05 ; .....#.#
                  .byte $05 ; .....#.#
                  .byte $0f ; ....####
                  
                  .byte $c0 ; ##......  -> $35e8 = Gfx_bd
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $40 ; .#......
                  .byte $40 ; .#......
                  .byte $f0 ; ####....
                  
                  .byte $03 ; ......##  -> $35f0 = Gfx_be
                  .byte $0e ; ....###.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $3c ; ..####..
                  
                  .byte $c0 ; ##......  -> $35f8 = Gfx_bf
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $54 ; .#.#.#..
                  .byte $1c ; ...###..
                  .byte $0c ; ....##..
                  
                  .byte $00 ; ........  -> $3600 = Gfx_c0
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3608 = Gfx_c1
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3610 = Gfx_c2
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......##
                  
                  .byte $00 ; ........  -> $3618 = Gfx_c3
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3620 = Gfx_c4
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ......#.  -> $3628 = Gfx_c5
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3630 = Gfx_c6
                  .byte $00 ; ........
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3638 = Gfx_c7
                  .byte $00 ; ........
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3640 = Gfx_c8
                  .byte $00 ; ........
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3648 = Gfx_c9
                  .byte $00 ; ........
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3650 = Gfx_ca
                  .byte $00 ; ........
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3658 = Gfx_cb
                  .byte $00 ; ........
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3660 = Gfx_cc
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3668 = Gfx_cd
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $00 ; ........  -> $3670 = Gfx_ce
                  .byte $02 ; ......#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $0a ; ....#.#.
                  .byte $02 ; ......#.
                  .byte $02 ; ......#.
                  
                  .byte $00 ; ........  -> $3678 = Gfx_cf
                  .byte $80 ; #.......
                  .byte $a0 ; #.#.....
                  .byte $88 ; #...#...
                  .byte $88 ; #...#...
                  .byte $a0 ; #.#.....
                  .byte $80 ; #.......
                  .byte $80 ; #.......
                  
                  .byte $03 ; ......##  -> $3680 = Gfx_d0
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $17 ; ...#.###
                  .byte $c0 ; ##......
                  .byte $c0 ; ##......
                  .byte $00 ; ........
                  
                  .byte $c0 ; ##......  -> $3688 = Gfx_d1
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $0f ; ....####
                  
                  .byte $03 ; ......##  -> $3690 = Gfx_d2
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $17 ; ...#.###
                  .byte $c0 ; ##......
                  .byte $c0 ; ##......
                  .byte $00 ; 00
                  
                  .byte $c0 ; ##......  -> $3698 = Gfx_d3
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $04 ; .....#..
                  .byte $04 ; .....#..
                  .byte $0f ; ....####
                  
                  .byte $03 ; ......##  -> $36a0 = Gfx_d4
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $07 ; .....###
                  .byte $d5 ; ##.#.#.#
                  .byte $c0 ; ##......
                  .byte $00 ; ........
                  
                  .byte $c0 ; ##......  -> $36a8 = Gfx_d5
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $03 ; ......##  -> $36b0 = Gfx_d6
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $15 ; ...#.#.#
                  .byte $34 ; ..##.#..
                  .byte $30 ; ..##....
                  
                  .byte $c0 ; ##......  -> $36b8 = Gfx_d7
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
                  
                  .byte $03 ; ......##  -> $36c0 = Gfx_d8
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $01 ; .......#
                  .byte $0d ; ....##.#
                  .byte $0c ; ....##..
                  
                  .byte $c0 ; ##......  -> $36c8 = Gfx_d9
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $40 ; .#......
                  .byte $40 ; .#......
                  .byte $f0 ; ####....
                  
                  .byte $03 ; ....##..  -> $36d0 = Gfx_da
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $01 ; .......#
                  .byte $01 ; .......#
                  .byte $03 ; ......##
                  
                  .byte $c0 ; ##......  -> $36d8 = Gfx_db
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $50 ; .#.#....
                  .byte $50 ; .#.#....
                  .byte $c0 ; ##......
                  
                  .byte $03 ; ......##  -> $36e0 = Gfx_dc
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $01 ; .......#
                  .byte $01 ; .......#
                  .byte $0f ; ....####
                  
                  .byte $c0 ; ##......  -> $36e8 = Gfx_dd
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $c0 ; ##......
                  .byte $50 ; .#.#....
                  .byte $50 ; .#.#....
                  .byte $f0 ; ####....
                  
                  .byte $03 ; ......##  -> $36f0 = Gfx_de
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $02 ; ......#.
                  .byte $03 ; ......##
                  .byte $15 ; ...#.#.#
                  .byte $34 ; .#....##
                  .byte $30 ; ..##....
                  
                  .byte $c0 ; ##......  -> $36f8 = Gfx_df
                  .byte $b0 ; #.##....
                  .byte $c0 ; ##......
                  .byte $80 ; #.......
                  .byte $d0 ; ##.#....
                  .byte $10 ; ...#....
                  .byte $10 ; ...#....
                  .byte $3c ; ..####..
; ------------------------------------------------------------------------------------------------------------- ;
