; ------------------------------------------------------------------------------------------------------------- ;
; 
; ------------------------------------------------------------------------------------------------------------- ;
T_8b86            .byte $20                       ; garbage
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $d5
                  .byte $81
                  .byte $79
                  .byte $00
                  .byte $3a
                  .byte $53
                  .byte $4b
                  .byte $34
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $e2
                  .byte $81
                  .byte $79
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $50
                  .byte $58
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $ec
                  .byte $81
                  .byte $79
                  .byte $00
                  .byte $3a
                  .byte $45
                  .byte $58
                  .byte $49
                  .byte $54
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $ef
                  .byte $81
                  .byte $79
                  .byte $00
                  .byte $4f
                  .byte $50
                  .byte $54
                  .byte $49
                  .byte $4f
                  .byte $4e
                  .byte $a8
                  .byte $00
                  .byte $f0
                  .byte $81
                  .byte $00
                  .byte $00
                  .byte $3a
                  .byte $45
                  .byte $58
                  .byte $49
                  .byte $54
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $0e
                  .byte $82
                  .byte $7a
                  .byte $00
                  .byte $4f
                  .byte $55
                  .byte $54
                  .byte $57
                  .byte $41
                  .byte $4c
                  .byte $a8
                  .byte $00
                  .byte $0f
                  .byte $82
                  .byte $00
                  .byte $00
                  .byte $54
                  .byte $54
                  .byte $53
                  .byte $43
                  .byte $45
                  .byte $4e
                  .byte $a8
                  .byte $00
                  .byte $27
                  .byte $82
                  .byte $00
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $31
                  .byte $a8
                  .byte $00
                  .byte $29
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $34
                  .byte $a8
                  .byte $00
                  .byte $4e
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $35
                  .byte $a8
                  .byte $00
                  .byte $65
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $36
                  .byte $a8
                  .byte $00
                  .byte $7c
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $53
                  .byte $4b
                  .byte $31
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $92
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $37
                  .byte $a8
                  .byte $00
                  .byte $96
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $38
                  .byte $a8
                  .byte $00
                  .byte $ad
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $39
                  .byte $a8
                  .byte $00
                  .byte $c4
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $53
                  .byte $4b
                  .byte $32
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $d7
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $41
                  .byte $a8
                  .byte $00
                  .byte $db
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $42
                  .byte $a8
                  .byte $00
                  .byte $f2
                  .byte $82
                  .byte $7c
                  .byte $00
                  .byte $46
                  .byte $52
                  .byte $45
                  .byte $51
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $03
                  .byte $83
                  .byte $00
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $43
                  .byte $a8
                  .byte $00
                  .byte $09
                  .byte $83
                  .byte $7c
                  .byte $00
                  .byte $42
                  .byte $4c
                  .byte $55
                  .byte $45
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $8d
                  .byte $83
                  .byte $00
                  .byte $00
                  .byte $3a
                  .byte $53
                  .byte $4b
                  .byte $30
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $91
                  .byte $83
                  .byte $7d
                  .byte $00
                  .byte $59
                  .byte $45
                  .byte $4c
                  .byte $4c
                  .byte $4f
                  .byte $57
                  .byte $a8
                  .byte $00
                  .byte $a1
                  .byte $83
                  .byte $00
                  .byte $00
                  .byte $3a
                  .byte $53
                  .byte $4b
                  .byte $30
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $a5
                  .byte $83
                  .byte $7e
                  .byte $00
                  .byte $4d
                  .byte $55
                  .byte $53
                  .byte $50
                  .byte $4c
                  .byte $59
                  .byte $a8
                  .byte $00
                  .byte $ac
                  .byte $83
                  .byte $00
                  .byte $00
                  .byte $3a
                  .byte $53
                  .byte $4b
                  .byte $30
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $b3
                  .byte $83
                  .byte $7f
                  .byte $00
                  .byte $3a
                  .byte $53
                  .byte $4b
                  .byte $31
                  .byte $20
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $fd
                  .byte $83
                  .byte $7f
                  .byte $00
                  .byte $3a
                  .byte $45
                  .byte $58
                  .byte $49
                  .byte $54
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $2d
                  .byte $84
                  .byte $7f
                  .byte $00
                  .byte $4d
                  .byte $41
                  .byte $53
                  .byte $51
                  .byte $55
                  .byte $45
                  .byte $a8
                  .byte $00
                  .byte $2e
                  .byte $84
                  .byte $00
                  .byte $00
                  .byte $3a
                  .byte $4c
                  .byte $4f
                  .byte $4f
                  .byte $50
                  .byte $20
                  .byte $a8
                  .byte $00
                  .byte $23
; ------------------------------------------------------------------------------------------------------------- ;
T_8cf3            .byte $55 ; u
                  .byte $31 ; 1
                  .byte $3a ; :
                  .byte $35 ; 5
                  .byte $2c ; ,
                  .byte $30 ; 0
                  .byte $2c ; ,
                  .byte $31 ; 1
                  .byte $38 ; 8
                  .byte $2c ; ,
                  .byte $31 ; 1
                  .byte $38 ; 8
; ------------------------------------------------------------------------------------------------------------- ;
                  jsr CLALL                       ; KERNAL - $FFE7 = Close all Files
                  lda #$00
                  jsr SETNAM                      ; KERNAL - $FFBD = Set Filename Parameters
                  lda #$0f
                  ldx #$08
                  ldy #$0f
                  jsr SETLFS                      ; KERNAL - $FFBA = Set Logical File Parameters
                  jsr OPEN                        ; KERNAL - $FFC0 = Open a Logical File
                  lda #$01
                  ldx #$f2
                  ldy #$8c
                  jsr SETNAM                      ; KERNAL - $FFBD = Set Filename Parameters
                  lda #$05
                  ldx #$08
                  ldy #$05
                  jsr SETLFS                      ; KERNAL - $FFBA = Set Logical File Parameters
                  jsr OPEN                        ; KERNAL - $FFC0 = Open a Logical File
                  ldx #$0f
                  jsr CHKOUT                      ; KERNAL - $FFC9 = Define an Output Channel
                  ldx #$00
B_8d2f            lda T_8cf3,x
                  jsr CHROUT                      ; KERNAL - $FFD2 = Output a Character
                  inx
                  cpx #$0c
                  bne B_8d2f
                  
                  jsr CLRCHN                      ; KERNAL - $FFCC = Restore Default Devices
                  ldx #$0f
                  jsr CHKIN                       ; KERNAL - $FFC6 = Define an Input Channel
                  ldx #$00
                  jsr CHRIN                       ; KERNAL - $FFCF = Input a Character
                  cmp #$32
                  bne B_8d6a
                  
                  jsr CHRIN                       ; KERNAL - $FFCF = Input a Character
                  cmp #$33
                  bne B_8d6a
                  
                  ldy #$14
B_8d54            jsr CHRIN                       ; KERNAL - $FFCF = Input a Character
                  dey
                  bne B_8d54
                  
                  lda #$05
                  jsr CLOSE                       ; KERNAL - $FFC3 = Close a Logical File
                  lda #$0f
                  jsr CLOSE                       ; KERNAL - $FFC3 = Close a Logical File
                  jsr CLRCHN                      ; KERNAL - $FFCC = Restore Default Devices
                  jmp GameStart
; ------------------------------------------------------------------------------------------------------------- ;
B_8d6a            lda #$70
                  sta $fb                         ; pressed key 1st col value
                  lda #$00
                  sta $fa
                  tax
                  tay
B_8d74            sta ($fa),y
                  iny
                  bne B_8d74
                  
                  inx
                  cpx #$20
                  bne B_8d74
                  
                  jmp GameStart
; ------------------------------------------------------------------------------------------------------------- ;
                  .byte $55
                  .byte $00
                  .byte $ff
                  .byte $00
                  .byte $50
                  .byte $00
                  .byte $ff
                  .byte $ef
                  .byte $ff
                  .byte $00
                  .byte $ff
                  .byte $00
                  .byte $ff
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
                  .byte $00
; ------------------------------------------------------------------------------------------------------------- ;
