; ------------------------------------------------------------------------------------------------------------- ;
; BASIC interpreter ROM ($A000 - $BFFF)
; ------------------------------------------------------------------------------------------------------------- ;
;Restart      = $a000 ; Vectors                               WORD
STMDSP        = $a00c ; BASIC Command  Vectors                WORD
FUNDSP        = $a052 ; BASIC Function Vectors                WORD
OPTAB         = $a080 ; BASIC Operator Vectors                WORD
RESLST        = $a09e ; BASIC Command  Keyword Table          DATA
MSCLST        = $a129 ; BASIC Misc     Keyword Table          DATA
OPLIST        = $a140 ; BASIC Operator Keyword Table          DATA
FUNLST        = $a14d ; BASIC Function Keyword Table          DATA
ERRTAB        = $a19e ; Error Message  Table                  DATA
ERRPTR        = $a328 ; Error Message  Pointers               WORD
OKK           = $a364 ; Misc  Messages                        TEXT
FNDFOR        = $a38a ; Find FOR/GOSUB Entry on Stack
BLTU          = $a3b8 ; Open Space in Memory
GETSTK        = $a3fb ; Check Stack Depth
REASON        = $a408 ; Check Memory Overlap
OMERR         = $a435 ; Output ?OUT OF MEMORY Error
ERROR         = $a437 ; Error Routine
ERRFIN        = $a469 ; Break Entry
READY         = $a474 ; Restart BASIC
MAIN          = $a480 ; Input & Identify BASIC Line
MAIN1         = $a49c ; Get Line Number & Tokenise Text
INSLIN        = $a4a2 ; Insert BASIC Text
LINKPRG       = $a533 ; Rechain Lines
INLIN         = $a560 ; Input Line Into Buffer
CRUNCH        = $a579 ; Tokenise Input Buffer
FNDLIN        = $a613 ; Search for Line Number
_SCRTCH_      = $a642 ; Perform [new]
_CLEAR_       = $a65e ; Perform [clr]
STXPT         = $a68e ; Reset TXTPTR
_LIST_        = $a69c ; Perform [list]
QPLOP         = $a717 ; Handle LIST Character
_FOR_         = $a742 ; Perform [for]
NEWSTT        = $a7ae ; BASIC Warm Start
CKEOL         = $a7c4 ; Check End of Program
GONE          = $a7e1 ; Prepare to execute statement
GONE3         = $a7ed ; Perform BASIC Keyword
_RESTORE_     = $a81d ; Perform [restore]
_STOP_        = $a82c ; Perform [stop], [end], break
_CONT_        = $a857 ; Perform [cont]
_RUN_         = $a871 ; Perform [run]
_GOSUB_       = $a883 ; Perform [gosub]
_GOTO_        = $a8a0 ; Perform [goto]
_RETURN_      = $a8d2 ; Perform [return]
_DATA_        = $a8f8 ; Perform [data]
DATAN         = $a906 ; Search for Next Statement / Line
_IF_          = $a928 ; Perform [if]
_REM_         = $a93b ; Perform [rem]
_ONGOTO_      = $a94b ; Perform [on]
LINGET        = $a96b ; Fetch linnum From BASIC
_LET_         = $a9a5 ; Perform [let]
PUTINT        = $a9c4 ; Assign Integer
PTFLPT        = $a9d6 ; Assign Floating Point
PUTSTR        = $a9d9 ; Assign String
PUTTIM        = $a9e3 ; Assign TI$
GETSPT        = $aa2c ; Add Digit to FAC#1
_PRINTN_      = $aa80 ; Perform [print]#
_CMD_         = $aa86 ; Perform [cmd]
STRDON        = $aa9a ; Print String From Memory
_PRINT_       = $aaa0 ; Perform [print]
VAROP         = $aab8 ; Output Variable
CRDO          = $aad7 ; Output CR/LF
COMPRT        = $aae8 ; Handle comma, TAB(, SPC(
STROUT        = $ab1e ; Output String
OUTSPC        = $ab3b ; Output Format Character
DOAGIN        = $ab4d ; Handle Bad Data
_GET_         = $ab7b ; Perform [get]
_INPUTN_      = $aba5 ; Perform [input#]
_INPUT_       = $abbf ; Perform [input]
BUFFUL        = $abea ; Read Input Buffer
QINLIN        = $abf9 ; Do Input Prompt
_READ_        = $ac06 ; Perform [read]
RDGET         = $ac35 ; General Purpose Read Routine
EXINT         = $acfc ; Input Error Messages                  TEXT
_NEXT_        = $ad1e ; Perform [next]
DONEXT        = $ad61 ; Check Valid Loop
FRMNUM        = $ad8a ; Confirm Result
FRMEVL        = $ad9e ; Evaluate Expression in Text
EVAL          = $ae83 ; Evaluate Single Term
PIVAL         = $aea8 ; Constant - pi                         DATA
QDOT          = $aead ; Continue Expression
PARCHK        = $aef1 ; Expression in Brackets
CHKCLS        = $aef7 ; Confirm Character
;             = $aef7 ; -test ')'-
;             = $aefa ; -test '('-
;             = $aefd ; -test comma-
SYNERR        = $af08 ; Output ?SYNTAX Error
DOMIN         = $af0d ; Set up NOT Function
RSVVAR        = $af14 ; Identify Reserved Variable
ISVAR         = $af28 ; Search for Variable
TISASC        = $af48 ; Convert TI to ASCII String
ISFUN         = $afa7 ; Identify Function Type
STRFUN        = $afb1 ; Evaluate String Function
NUMFUN        = $afd1 ; Evaluate Numeric Function
_OROP_        = $afe6 ; Perform [or], [and]
_DOREL_       = $b016 ; Perform <, =, >
NUMREL        = $b01b ; Numeric Comparison
STRREL        = $b02e ; String Comparison
_DIM_         = $b07e ; Perform [dim]
PTRGET        = $b08b ; Identify Variable
ORDVAR        = $b0e7 ; Locate Ordinary Variable
NOTFNS        = $b11d ; Create New Variable
NOTEVL        = $b128 ; Create Variable
ARYGET        = $b194 ; Allocate Array Pointer Space
N32768        = $b1a5 ; Constant 32768 in Flpt        DATA
FACINX        = $b1aa ; FAC#1 to Integer in (AC/YR)
INTIDX        = $b1b2 ; Evaluate Text for Integer
AYINT         = $b1bf ; FAC#1 to Positive Integer
ISARY         = $b1d1 ; Get Array Parameters
FNDARY        = $b218 ; Find Array
BSERR         = $b245 ; ?BAD SUBSCRIPT/?ILLEGAL QUANTITY
NOTFDD        = $b261 ; Create Array
INLPN2        = $b30e ; Locate Element in Array
UMULT         = $b34c ; Number of Bytes in Subscript
_FRE_         = $b37d ; Perform [fre]
GIVAYF        = $b391 ; Convert Integer in (AC/YR) to Flpt
_POS_         = $b39e ; Perform [pos]
ERRDIR        = $b3a6 ; Confirm Program Mode
GETFNM        = $b3e1 ; Check Syntax of FN
_FNDOER_      = $b3f4 ; Perform [fn]
_STRD_        = $b465 ; Perform [str$]
STRLIT        = $b487 ; Set Up String
PUTNW1        = $b4d5 ; Save String Descriptor
GETSPA        = $b4f4 ; Allocate Space for String
GARBAG        = $b526 ; Garbage Collection
DVARS         = $b5bd ; Search for Next String
GRBPAS        = $b606 ; Collect a String
CAT           = $b63d ; Concatenate Two Strings
MOVINS        = $b67a ; Store String in High RAM
_FRESTR_      = $b6a3 ; Perform String Housekeeping
FREFAC        = $b6db ; Clean Descriptor Stack
_CHRD_        = $b6ec ; Perform [chr$]
_LEFTD_       = $b700 ; Perform [left$]
_RIGHTD_      = $b72c ; Perform [right$]
_MIDD_        = $b737 ; Perform [mid$]
PREAM         = $b761 ; Pull sTring Parameters
_LEN_         = $b77c ; Perform [len]
LEN1          = $b782 ; Exit String Mode
_ASC_         = $b78b ; Perform [asc]
GTBYTC        = $b79b ; Evaluate Text to 1 Byte in XR
_VAL_         = $b7ad ; Perform [val]
STRVAL        = $b7b5 ; Convert ASCII String to Flpt
GETNUM        = $b7eb ; Get parameters for POKE/WAIT
GETADR        = $b7f7 ; Convert FAC#1 to Integer in LINNUM
_PEEK_        = $b80d ; Perform [peek]
_POKE_        = $b824 ; Perform [poke]
_WAIT_        = $b82d ; Perform [wait]
FADDH         = $b849 ; Add 0.5 to FAC#1
_FSUB_        = $b850 ; Perform Subtraction
FADD5         = $b862 ; Normalise Addition
_FADD_        = $b867 ; Perform Addition
NEGFAC        = $b947 ; 2s Complement FAC#1
OVERR         = $b97e ; Output ?OVERFLOW Error
MULSHF        = $b983 ; Multiply by Zero Byte
FONE          = $b9bc ; Table of Flpt Constants               DATA
_LOG_         = $b9ea ; Perform [log]
_FMULT_       = $ba28 ; Perform Multiply
MULPLY        = $ba59 ; Multiply by a Byte
CONUPK        = $ba8c ; Load FAC#2 From Memory
MULDIV        = $bab7 ; Test Both Accumulators
MLDVEX        = $bad4 ; Overflow / Underflow
MUL10         = $bae2 ; Multiply FAC#1 by 10
TENC          = $baf9 ; Constant 10 in Flpt                   DATA
DIV10         = $bafe ; Divide FAC#1 by 10
FDIV          = $bb07 ; Divide FAC#2 by Flpt at (AC/YR)
FDIVT         = $bb0f ; Divide FAC#2 by FAC#1
MOVFM         = $bba2 ; Load FAC#1 From Memory
MOV2F         = $bbc7 ; Store FAC#1 in Memory
MOVFA         = $bbfc ; Copy FAC#2 into FAC#1
MOVAF         = $bc0c ; Copy FAC#1 into FAC#2
ROUND         = $bc1b ; Round FAC#1
SIGN          = $bc2b ; Check Sign of FAC#1
_SGN_         = $bc39 ; Perform [sgn]
_ABS_         = $bc58 ; Perform [abs]
FCOMP         = $bc5b ; Compare FAC#1 With Memory
QINT          = $bc9b ; Convert FAC#1 to Integer
_INT_         = $bccc ; Perform [int]
FIN           = $bcf3 ; Convert ASCII String to a Number in FAC#1
N0999         = $bdb3 ; String Conversion Constants           DATA
INPRT         = $bdc2 ; Output 'IN' and Line Number
FOUT          = $bddd ; Convert FAC#1 to ASCII String
FOUTIM        = $be68 ; Convert TI to String
FHALF         = $bf11 ; Table of Constants                    DATA
_SQR_         = $bf71 ; Perform [sqr]
_FPWRT_       = $bf7b ; Perform power ($)
NEGOP         = $bfb4 ; Negate FAC#1
LOGEB2        = $bfbf ; Table of Constants                    DATA
_EXP_         = $bfed ; Perform [exp]
; ------------------------------------------------------------------------------------------------------------- ;
; 
; ------------------------------------------------------------------------------------------------------------- ;
;             = $e000 ; Perform [exp] - continued from BASIC ROM
POLYX         = $e043 ; Series Evaluation
RMULC         = $e08d ; Constants for RND                     DATA
_RND_         = $e097 ; Perform [rnd]
BIOERR        = $e0f9 ; Handle I/O Error in BASIC
BCHOUT        = $e10c ; Output Character
BCHIN         = $e112 ; Input Character
BCKOUT        = $e118 ; Set Up For Output
BCKIN         = $e11e ; Set Up For Input
BGETIN        = $e124 ; Get One Character
_SYS_         = $e12a ; Perform [sys]
_SAVET_       = $e156 ; Perform [save]
_VERFYT_      = $e165 ; Perform [verify / load]
_OPENT_       = $e1be ; Perform [open]
_CLOSET_      = $e1c7 ; Perform [close]
SLPARA        = $e1d4 ; Get Parameters For LOAD/SAVE
COMBYT        = $e200 ; Get Next One Byte Parameter
DEFLT         = $e206 ; Check Default Parameters
CMMERR        = $e20e ; Check For Comma
OCPARA        = $e219 ; Get Parameters For OPEN/CLOSE
_COS_         = $e264 ; Perform [cos]
_SIN_         = $e26b ; Perform [sin]
_TAN_         = $e2b4 ; Perform [tan]
PI2           = $e2e0 ; Table of Trig Constants               DATA
              = $     ;
;             = $e2e0 ; 1.570796327   pi/2
;             = $e2e5 ; 6.28318531    pi*2
;             = $e2ea ; 0.25
              = $     ;
;             = $e2ef ; #05 (counter)
;             = $e2f0 ; -14.3813907
;             = $e2f5 ; 42.0077971
;             = $e2fa ; -76.7041703
;             = $e2ff ; 81.6052237
;             = $e304 ; -41.3417021
;             = $e309 ; 6.28318531
              = $     ;
_ATN_         = $e30e ; Perform [atn]
ATNCON        = $e33e ; Table of ATN Constants                DATA
              = $     ;
;             = $e33e ; #0b (counter)
;             = $e3ef ; -0.000684793912
;             = $e344 ;  0.00485094216
;             = $e349 ; -0.161117018
;             = $e34e ;  0.034209638
;             = $e353 ; -0.0542791328
;             = $e358 ;  0.0724571965
;             = $e35d ; -0.0898023954
;             = $e362 ;  0.110932413
;             = $e367 ; -0.142839808
;             = $e36c ;  0.19999912
;             = $e371 ; -0.333333316
;             = $e376 ;  1.00
;             = $     ;
BASSFT        = $e37b ; BASIC Warm Start [RUNSTOP-RESTORE]
INIT          = $e394 ; BASIC Cold Start
INITAT        = $e3a2 ; CHRGET For Zero-page
RNDSED        = $e3ba ; RND Seed For zero-page                DATA
;             = $e3b2 ; 0.811635157
INITCZ        = $e3bf ; Initialize BASIC RAM
INITMS        = $e422 ; Output Power-Up Message
BVTRS         = $e447 ; Table of BASIC Vectors (for 0300)     WORD
INITV         = $e453 ; Initialize Vectors
WORDS         = $e45f ; Power-Up Message                      DATA
;             = $e4ad ; Patch for BASIC Call to CHKOUT
;             = $e4b7 ; Unused Bytes For Future Patches       EMPTY
;             = $e4da ; Reset Character Colour
;             = $e4e0 ; Pause After Finding Tape File
;             = $e4ec ; RS-232 Timing Table -- PAL            DATA
; ------------------------------------------------------------------------------------------------------------- ;
