; ------------------------------------------------------------------------------------------------------------- ;
; C64 Kernal=  ROM
; ------------------------------------------------------------------------------------------------------------- ;
_IOBASE       = $e500 ; Get I/O Address
_SCREEN       = $e505 ; Get Screen Size
_PLOT         = $e50a ; Put / Get Row And Column
CINT1         = $e518 ; Initialize I/O
;             = $e544 ; Clear Screen
;             = $e566 ; Home Cursor
;             = $e56c ; Set Screen Pointers
;             = $e59a ; Set I/O Defaults (Unused Entry)
;             = $e5a0 ; Set I/O Defaults
LP2           = $e5b4 ; Get Character From Keyboard Buffer
;             = $e5ca ; Input From Keyboard
;             = $e632 ; Input From Screen or Keyboard
;             = $e684 ; Quotes Test
;             = $e691 ; Set Up Screen Print
;             = $e6b6 ; Advance Cursor
;             = $e6ed ; Retreat Cursor
;             = $e701 ; Back on to Previous Line
;             = $e716 ; Output to Screen
;             = $e72a ; -unshifted characters-
;             = $e7d4 ; -shifted characters-
;             = $e87c ; Go to Next Line
;             = $e891 ; Output <CR>
;             = $e8a1 ; Check Line Decrement
;             = $e8b3 ; Check Line Increment
;             = $e8cb ; Set Colour Code
;             = $e8da ; Colour Code Table
;             = $e8ea ; Scroll Screen
;             = $e965 ; Open A Space On The Screen
;             = $e9c8 ; Move A Screen Line
;             = $e9e0 ; Syncronise Colour Transfer
;             = $e9f0 ; Set Start of Line
;             = $e9ff ; Clear Screen Line
;             = $ea13 ; Print To Screen
;             = $ea24 ; Syncronise Colour Pointer
;             = $ea31 ; Main IRQ Entry Point
_SCNKEY       = $ea87 ; Scan Keyboard
;             = $eadd ; Process Key Image
;             = $eb79 ; Pointers to Keyboard decoding tables  WORD
;             = $eb81 ; Keyboard 1 -- unshifted               DATA
;             = $ebc2 ; Keyboard 2 -- Shifted                 DATA
;             = $ec03 ; Keyboard 3 -- Commodore               DATA
;             = $ec44 ; Graphics/Text Control
;             = $ec78 ; Keyboard 4 -- Control                 DATA
;             = $ecb9 ; Video Chip Setup Table                DATA
;             = $ece7 ; Shift-Run Equivalent
;             = $ecf0 ; Low Byte Screen Line Addresses        DATA
_TALK         = $ed09 ; Send TALK Command on Serial Bus
_LISTEN       = $ed0c ; Send LISTEN Command on Serial Bus
;             = $ed40 ; Send Data On Serial Bus
;             = $edad ; Flag Errors
;             = $edad ; Status #80 - device not present
;             = $edb0 ; Status #03 - write timeout
_SECOND       = $edb9 ; Send LISTEN Secondary Address
;             = $edbe ; Clear ATN
_TKSA         = $edc7 ; Send TALK Secondary Address
;             = $edcc ; Wait For Clock
_CIOUT        = $eddd ; Send Serial Deferred
_UNTLK        = $edef ; Send UNTALK
_UNLSN        = $edfe ; Send UNLISTEN
_ACPTR        = $ee13 ; Receive From Serial Bus
;             = $ee85 ; Serial Clock On
;             = $ee8e ; Serial Clock Off
;             = $ee97 ; Serial Output 1
;             = $eea0 ; Serial Output 0
;             = $eea9 ; Get Serial Data And Clock In
;             = $eeb3 ; Delay 1 ms
;             = $eebb ; RS-232 Send
;             = $ef06 ; Send New RS-232 Byte
;             = $ef2e ; 'No DSR' / 'No CTS' Error
;             = $ef39 ; Disable Timer
;             = $ef4a ; Compute Bit Count
;             = $ef59 ; RS-232 Receive
;             = $ef7e ; Set Up To Receive
;             = $ef90 ; Process RS-232 Byte
;             = $efe1 ; Submit to RS-232
;             = $f00d ; No DSR (Data Set Ready) Error
;             = $f017 ; Send to RS-232 Buffer
;             = $f04d ; Input From RS-232
;             = $f086 ; Get From RS-232
;             = $f0a4 ; Serial Bus Idle
;             = $f0bd ; Table of Kernal I/O Messages          DATA
;             = $f12b ; Print Message if Direct
;             = $f12f ; Print Message
_GETIN        = $f13e ; Get a byte
_CHRIN        = $f157 ; Input a byte
;             = $f199 ; Get From Tape / Serial / RS-232
_CHROUT       = $f1ca ; Output One Character
_CHKIN        = $f20e ; Set Input Device
_CHKOUT       = $f250 ; Set Output Device
_CLOSE        = $f291 ; Close File
;             = $f30f ; Find File
;             = $f31f ; Set File values
_CLALL        = $f32f ; Abort All Files
_CLRCHN       = $f333 ; Restore Default I/O
_OPEN         = $f34a ; Open File
;             = $f3d5 ; Send Secondary Address
;             = $f409 ; Open RS-232
_LOAD         = $f49e ; Load RAM
;             = $f4b8 ; Load File From Serial Bus
;             = $f533 ; Load File From Tape
;             = $f5af ; Print "SEARCHING"
;             = $f5c1 ; Print Filename
;             = $f5d2 ; Print "LOADING / VERIFYING"
_SAVE         = $f5dd ; Save RAM
;             = $f5fa ; Save to Serial Bus
;             = $f659 ; Save to Tape
;             = $f68f ; Print "SAVING"
_UDTIM        = $f69b ; Bump Clock
_RDTIM        = $f6dd ; Get Time
_SETTIM       = $f6e4 ; Set Time
_STOP         = $f6ed ; Check STOP Key
;             = $f6fb ; Output I/O Error Messages
;             = $f6fb ; 'too many files'
;             = $f6fe ; 'file open'
;             = $f701 ; 'file not open'
;             = $f704 ; 'file not found'
;             = $f707 ; 'device not present'
;             = $f70a ; 'not input file'
;             = $f70d ; 'not output file'
;             = $f710 ; 'missing filename'
;             = $f713 ; 'illegal device number'
;             = $f72d ; Find Any Tape Header
;             = $f76a ; Write Tape Header
;             = $f7d0 ; Get Buffer Address
;             = $f7d7 ; Set Buffer Stat / End Pointers
;             = $f7ea ; Find Specific Tape Header
;             = $f80d ; Bump Tape Pointer
;             = $f817 ; Print "PRESS PLAY ON TAPE"
;             = $f82e ; Check Tape Status
;             = $f838 ; Print "PRESS RECORD..."
;             = $f841 ; Initiate Tape Read
;             = $f864 ; Initiate Tape Write
;             = $f875 ; Common Tape Code
;             = $f8d0 ; Check Tape Stop
;             = $f8e2 ; Set Read Timing
;             = $f92c ; Read Tape Bits
;             = $fa60 ; Store Tape Characters
;             = $fb8e ; Reset Tape Pointer
;             = $fb97 ; New Character Setup
;             = $fba6 ; Send Tone to Tape
;             = $fbc8 ; Write Data to Tape
;             = $fbcd ; IRQ Entry Point
;             = $fc57 ; Write Tape Leader
;             = $fc93 ; Restore Normal IRQ
;             = $fcb8 ; Set IRQ Vector
;             = $fcca ; Kill Tape Motor
;             = $fcd1 ; Check Read / Write Pointer
;             = $fcdb ; Bump Read / Write Pointer
;             = $fce2 ; Power-Up RESET Entry
;             = $fd02 ; Check For 8-ROM
;             = $fd12 ; 8-ROM Mask '80CBM'                    DATA
_RESTOR       = $fd15 ; Restore Kernal Vectors (at 0314)
_VECTOR       = $fd1a ; Change Vectors For User
;             = $fd30 ; Kernal Reset Vectors                  WORD
_RAMTAS       = $fd50 ; Initialise System Constants
;             = $fd9b ; IRQ Vectors For Tape I/O              WORD
_IOINIT       = $fda3 ; Initialise I/O
;             = $fddd ; Enable Timer
_SETNAM       = $fdf9 ; Set Filename
_SETLFS       = $fe00 ; Set Logical File Parameters
_READST       = $fe07 ; Get I/O Status Word
_SETMSG       = $fe18 ; Control OS Messages
_SETTMO       = $fe21 ; Set IEEE Timeout
_MEMTOP       = $fe25 ; Read / Set Top of Memory
_MEMBOT       = $fe34 ; Read / Set Bottom of Memory
;             = $fe43 ; NMI Transfer Entry
;             = $fe66 ; Warm Start Basic [BRK]
;             = $febc ; Exit Interrupt
;             = $fec2 ; RS-232 Timing Table - NTSC            DATA
;             = $fed6 ; NMI RS-232 In
;             = $ff07 ; NMI RS-232 Out
;             = $ff43 ; Fake IRQ Entry
;             = $ff48 ; IRQ Entry
_CINT         = $ff5b ; Initialize screen editor
;             = $ff80 ; Kernal Version Number [03]            DATA
; ------------------------------------------------------------------------------------------------------------- ;
; C64 Kernal Jump Table - see kernel.asm
; ------------------------------------------------------------------------------------------------------------- ;
;              ifnconst CINT
;CINT          = $ff81 ; jmp  $ff5b   _CINT    Init Editor & Video Chips
;IOINIT        = $ff84 ; jmp  $fd23   _IOINIT  Init I/O Devices, Ports & Timers
;RAMTAS        = $ff87 ; jmp  $fd50   _RAMTAS  Init Ram & Buffers
;RESTOR        = $ff8a ; jmp  $fd15   _RESTOR  Restore Vectors
;VECTOR        = $ff8d ; jmp  $fd1a   _VECTOR  Change Vectors For User
;SETMSG        = $ff90 ; jmp  $fe18   _SETMSG  Control OS Messages
;SECOND        = $ff93 ; jmp  $edb9   _SECND   Send SA After Listen
;TKSA          = $ff96 ; jmp  $edc7   _TKSA    Send SA After Talk
;MEMTOP        = $ff99 ; jmp  $fe25   _MEMTOP  Set/Read System RAM Top
;MEMBOT        = $ff9c ; jmp  $fe34   _MEMBOT  Set/Read System RAM Bottom
;SCNKEY        = $ff9f ; jmp  $ea87   _SCNKEY  Scan Keyboard
;SETTMO        = $ffa2 ; jmp  $fe21   _SETTMO  Set Timeout In IEEE
;ACPTR         = $ffa5 ; jmp  $ee13   _ACPTR   Handshake Serial Byte In
;CIOUT         = $ffa8 ; jmp  $eddd   _CIOUT   Handshake Serial Byte Out
;UNTLK         = $ffab ; jmp  $edef   _UNTALK  Command Serial Bus UNTALK
;UNLSN         = $ffae ; jmp  $edfe   _UNLSN   Command Serial Bus UNLISTEN
;LISTEN        = $ffb1 ; jmp  $ed0c   _LISTN   Command Serial Bus LISTEN
;TALK          = $ffb4 ; jmp  $ed09   _TALK    Command Serial Bus TALK
;READST        = $ffb7 ; jmp  $fe07   _READSS  Read I/O Status Word
;SETLFS        = $ffba ; jmp  $fe00   _SETLFS  Set Logical File Parameters
;SETNAM        = $ffbd ; jmp  $fdf9   _SETNAM  Set Filename
;OPEN          = $ffc0 ; jmp ($031a) IOPEN     Open Vector [f34a]
;CLOSE         = $ffc3 ; jmp ($031c) ICLOSE    Close Vector [f291]
;CHKIN         = $ffc6 ; jmp ($031e) ICHKIN    Set Input [f20e]
;CHKOUT        = $ffc9 ; jmp ($0320) ICHKOUT   Set Output [f250]
;CLRCHN        = $ffcc ; jmp ($0322) ICLRCH    Restore I/O Vector [f333]
;CHRIN         = $ffcf ; jmp ($0324) ICHRIN    Input Vector, chrin [f157]
;CHROUT        = $ffd2 ; jmp ($0326) ICHROUT   Output Vector, chrout [f1ca]
;LOAD          = $ffd5 ; jmp  $f49e   _LOAD    Load RAM From Device
;SAVE          = $ffd8 ; jmp  $f5dd   _SAVE    Save RAM To Device
;SETTIM        = $ffdb ; jmp  $f6e4   _SETTIM  Set Real-Time Clock
;RDTIM         = $ffde ; jmp  $f6dd   _RDTIM   Read Real-Time Clock
;STOP          = $ffe1 ; jmp ($0328) ISTOP     Test-Stop Vector [f6ed]
;GETIN         = $ffe4 ; jmp ($032a) IGETIN    Get From Keyboad [f13e]
;CLALL         = $ffe7 ; jmp ($032c) ICLALL    Close All Channels And Files [f32f]
;UDTIM         = $ffea ; jmp  $f69b   _UDTIM   Increment Real-Time Clock
;SCREEN        = $ffed ; jmp  $e505   _SCREEN  Return Screen Organization
;PLOT          = $fff0 ; jmp  $e50a   _PLOT    Read / Set Cursor X/Y Position
;IOBASE        = $fff3 ; jmp  $e500   _IOBASE  Return I/O Base Address
;              endif
; ------------------------------------------------------------------------------------------------------------- ;
; Vectors
; ------------------------------------------------------------------------------------------------------------- ;
;             = $fff6 ; [$5252]     -
;             = $fff8 ; [$5942]     SYSTEM
; ------------------------------------------------------------------------------------------------------------- ;
; Transfer Vectors
; ------------------------------------------------------------------------------------------------------------- ;
VNMI          = $fffa ; [$fe43]     NMI
VRES          = $fffc ; [$fce2]     RESET
VBRK          = $fffe ; [$ff48]     IRQ
; ------------------------------------------------------------------------------------------------------------- ;
