.setcpu "HUC6280"

.include "../common/platform.inc"

VDC_STATUS  = $0000
VDC_DATA_L  = $0002
VDC_DATA_H  = $0003
VCE_CTRL    = $0400
VCE_ADDR_L  = $0402
VCE_ADDR_H  = $0403
VCE_DATA_L  = $0404
VCE_DATA_H  = $0405
JOYPAD      = $1000

VDC_MAWR = $00
VDC_DATA = $02
VDC_CR   = $05
VDC_BXR  = $07
VDC_BYR  = $08
VDC_MWR  = $09
VDC_HSR  = $0A
VDC_HDR  = $0B
VDC_VSR  = $0C
VDC_VDR  = $0D
VDC_VCR  = $0E

; 32x32 BAT occupies VDC words $0000-$03ff. One 8x8 4bpp tile consumes
; 16 words, so tile index $40 starts at VDC word $0400.
PCE_PATTERN_WORD = $0400
PCE_PATTERN_TILE = $0040

.segment "BSS"
pad_result:      .res 1
pce_raw_dpad:    .res 1
pce_raw_buttons: .res 1

.segment "CODE"

.proc platform_init
    sei
    csh

    ; VCE: 5 MHz dot clock.
    stz VCE_CTRL

    ; Dedicated HuC6280 VDC instructions are now the canonical PCE register
    ; access path. The previous ordinary memory-mapped register selection did
    ; not reliably reach the VDC in Mednafen.

    ; Display/IRQs off, VRAM auto-increment = +1 word.
    st0 #VDC_CR
    st1 #$00
    st2 #$00

    ; Known-good 256x224 timing.
    st0 #VDC_HSR
    st1 #$02
    st2 #$02

    st0 #VDC_HDR
    st1 #$1f
    st2 #$04

    st0 #VDC_VSR
    st1 #$07
    st2 #$0d

    st0 #VDC_VDR
    st1 #$df
    st2 #$00

    st0 #VDC_VCR
    st1 #$03
    st2 #$00

    ; 32x32 BAT and zero scroll.
    st0 #VDC_MWR
    st1 #$00
    st2 #$00

    st0 #VDC_BXR
    st1 #$00
    st2 #$00

    st0 #VDC_BYR
    st1 #$00
    st2 #$00

    ; Upload the converted Boulder Dash C64 characters to VRAM word $0400.
    ; TIA alternates its destination between $0002/$0003, which exactly
    ; matches the VDC data low/high port pair after VDC_DATA has been selected.
    st0 #VDC_MAWR
    st1 #<PCE_PATTERN_WORD
    st2 #>PCE_PATTERN_WORD
    st0 #VDC_DATA
    tia bd_charset_pce, VDC_DATA_L, bd_charset_pce_bytes

    ; Fill the complete BAT with Chr_00 (blank tile $40). Using the dedicated
    ; ST1/ST2 path keeps this on the same proven VDC write mechanism as the
    ; full-white diagnostic test.
    st0 #VDC_MAWR
    st1 #$00
    st2 #$00
    st0 #VDC_DATA

    ldy #$04
@bat_page:
    ldx #$00
@bat_blank:
    st1 #<PCE_PATTERN_TILE
    st2 #>PCE_PATTERN_TILE
    inx
    bne @bat_blank
    dey
    bne @bat_page

    ; Replace the first 64 BAT entries with Chr_00..Chr_3f. The table is
    ; generated by ca65 below; TIA again alternates low/high VDC data ports.
    st0 #VDC_MAWR
    st1 #$00
    st2 #$00
    st0 #VDC_DATA
    tia pce_test_bat, VDC_DATA_L, 128

    ; BG palette 0: dark blue background and white set pixels.
    stz VCE_ADDR_L
    stz VCE_ADDR_H
    lda #$03
    sta VCE_DATA_L
    stz VCE_DATA_H
    lda #$ff
    sta VCE_DATA_L
    lda #$01
    sta VCE_DATA_H

    ; Backdrop/border blue.
    stz VCE_ADDR_L
    lda #$01
    sta VCE_ADDR_H
    lda #$03
    sta VCE_DATA_L
    stz VCE_DATA_H

    ; Background on + VBlank source; VRAM increment remains +1.
    st0 #VDC_CR
    st1 #$88
    st2 #$00

    lda #$03
    sta JOYPAD
    lda #$01
    sta JOYPAD
    rts
.endproc

.proc platform_wait_frame
@wait_vblank:
    lda VDC_STATUS
    and #$20
    beq @wait_vblank
    rts
.endproc

.proc platform_read_pad
    lda #$01
    sta JOYPAD
    nop
    nop
    lda JOYPAD
    and #$0f
    eor #$0f
    sta pce_raw_dpad

    stz JOYPAD
    nop
    nop
    lda JOYPAD
    and #$0f
    eor #$0f
    sta pce_raw_buttons

    stz pad_result

    lda pce_raw_dpad
    and #%00001000
    beq :+
    lda pad_result
    ora #PAD_LEFT
    sta pad_result
:
    lda pce_raw_dpad
    and #%00000100
    beq :+
    lda pad_result
    ora #PAD_RIGHT
    sta pad_result
:
    lda pce_raw_dpad
    and #%00000001
    beq :+
    lda pad_result
    ora #PAD_UP
    sta pad_result
:
    lda pce_raw_dpad
    and #%00000010
    beq :+
    lda pad_result
    ora #PAD_DOWN
    sta pad_result
:
    lda pce_raw_buttons
    and #%00000001
    beq :+
    lda pad_result
    ora #PAD_FIRE
    sta pad_result
:
    lda pce_raw_buttons
    and #%00001000
    beq :+
    lda pad_result
    ora #PAD_START
    sta pad_result
:
    lda pce_raw_buttons
    and #%00000100
    beq :+
    lda pad_result
    ora #PAD_SELECT
    sta pad_result
:
    lda pad_result
    rts
.endproc

.proc platform_video_begin
    rts
.endproc

.proc platform_video_end
    rts
.endproc

.proc platform_audio_tick
    ; Deferred milestone: HuC6280 PSG music and SFX backend.
    rts
.endproc

.segment "RODATA"

; BAT entries for the first 64 converted characters. Bits 11..0 are the tile
; index, bits 15..12 select BG palette 0.
pce_test_bat:
.repeat 64, I
    .byte <(PCE_PATTERN_TILE + I), >(PCE_PATTERN_TILE + I)
.endrepeat

.include "../../build/generated/pce/charset.inc"
