#!/usr/bin/env python3
"""Convert Boulder Dash C64 1bpp character data to console 4bpp tiles.

The source file contains labels Chr_XX followed by eight .byte rows. Each C64
character is therefore an 8x8 1bpp tile. For the first porting stage we map
set pixels to palette index 1 and clear pixels to palette index 0.

SNES 4bpp and HuC6270/PCE 4bpp both use 32 bytes per 8x8 tile in planar-pair
layout: plane 0/1 rows first, then plane 2/3 rows. With only palette indices
0/1, plane 0 contains the original C64 bitmap and the other three planes are 0.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

LABEL_RE = re.compile(r"^\s*Chr_([0-9A-Fa-f]{2})\b")
BYTE_RE = re.compile(r"\.byte\s+\$([0-9A-Fa-f]{2})", re.IGNORECASE)


def read_characters(path: Path) -> list[tuple[int, list[int]]]:
    chars: list[tuple[int, list[int]]] = []
    current_index: int | None = None
    rows: list[int] = []

    def finish() -> None:
        nonlocal current_index, rows
        if current_index is None:
            return
        if len(rows) != 8:
            raise ValueError(
                f"Chr_{current_index:02x} has {len(rows)} rows; expected exactly 8"
            )
        chars.append((current_index, rows.copy()))
        current_index = None
        rows = []

    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        label = LABEL_RE.match(line)
        if label:
            if current_index is not None:
                finish()
            current_index = int(label.group(1), 16)

        if current_index is not None:
            value = BYTE_RE.search(line)
            if value:
                rows.append(int(value.group(1), 16))
                if len(rows) == 8:
                    finish()
                elif len(rows) > 8:
                    raise ValueError(
                        f"Chr_{current_index:02x} has more than 8 rows near line {line_no}"
                    )

    if current_index is not None:
        finish()

    if not chars:
        raise ValueError("no Chr_XX definitions found")

    seen: set[int] = set()
    for index, _ in chars:
        if index in seen:
            raise ValueError(f"duplicate Chr_{index:02x}")
        seen.add(index)

    return chars


def encode_4bpp(rows: list[int]) -> bytes:
    out = bytearray()
    for row in rows:
        out.extend((row, 0x00))
    for _row in rows:
        out.extend((0x00, 0x00))
    assert len(out) == 32
    return bytes(out)


def emit_ca65(path: Path, label: str, chars: list[tuple[int, list[int]]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "; Generated by scripts/convert-charset.py -- do not edit.",
        f"; {len(chars)} C64 characters, 32 bytes per 4bpp tile.",
        "",
        f"{label}:",
    ]

    for index, rows in chars:
        data = encode_4bpp(rows)
        lines.append(f"    ; Chr_{index:02X}")
        for offset in range(0, 32, 16):
            chunk = data[offset : offset + 16]
            lines.append("    .byte " + ", ".join(f"${b:02X}" for b in chunk))

    lines += [
        f"{label}_end:",
        f"{label}_count = {len(chars)}",
        f"{label}_bytes = {len(chars) * 32}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument(
        "--limit",
        type=int,
        default=64,
        help="maximum number of Chr_XX tiles to convert (default: 64)",
    )
    parser.add_argument("--snes-out", type=Path, required=True)
    parser.add_argument("--pce-out", type=Path, required=True)
    args = parser.parse_args()

    chars = read_characters(args.source)
    chars.sort(key=lambda item: item[0])
    if args.limit <= 0:
        raise SystemExit("--limit must be greater than zero")
    chars = chars[: args.limit]

    emit_ca65(args.snes_out, "bd_charset_snes", chars)
    emit_ca65(args.pce_out, "bd_charset_pce", chars)

    print(f"converted {len(chars)} C64 characters")
    print(f"SNES: {args.snes_out}")
    print(f"PCE : {args.pce_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
