#!/usr/bin/env python3
from pathlib import Path
import argparse

COLS = 40
ROWS = 22

T_EMPTY = 0x00
T_SOIL = 0x01
T_WALL_STONE = 0x02
T_WALL_STEEL = 0x07
T_BOULDER = 0x10
T_DIAMOND = 0x14
T_BIRTH = 0x25
T_EXIT_CLOSED = 0x04

SEED = 0x0A
START = 0x00
RND_OBJECTS = (T_EMPTY, T_BOULDER, T_DIAMOND, T_EMPTY)
RND_PROBS = (0x3C, 0x32, 0x09, 0x00)


def rnd_step(seed: int, start: int):
    # Exact 8-bit behaviour of GetValPseudoRND in BoulderDashI.asm.
    p1 = 0x80 if (start & 0x02) else 0x00
    p2 = (seed >> 1) & 0x7F
    seed_sum = seed + (0x80 if (seed & 0x01) else 0x00) + 0x13
    carry = 1 if seed_sum > 0xFF else 0
    seed = seed_sum & 0xFF
    start = (start + p1 + p2 + carry) & 0xFF
    return seed, start, start


def build_full_cave():
    cave = [[T_EMPTY for _ in range(COLS)] for _ in range(ROWS)]
    seed = SEED
    start = START

    # Preserve the original 40-column RNG stream for every generated row.
    for row in range(1, ROWS):
        for col in range(COLS):
            seed, start, value = rnd_step(seed, start)
            tile = T_SOIL
            for obj, prob in zip(RND_OBJECTS, RND_PROBS):
                if value < prob:
                    tile = obj
            cave[row][col] = tile

    # Steel frame around the original 40x22 logical cave.
    for col in range(COLS):
        cave[0][col] = T_WALL_STEEL
        cave[ROWS - 1][col] = T_WALL_STEEL
    for row in range(ROWS):
        cave[row][0] = T_WALL_STEEL
        cave[row][COLS - 1] = T_WALL_STEEL

    # Cave 1 variable commands from B1_CaveData.asm.
    for col in range(1, 31):
        cave[9][col] = T_WALL_STONE
    for col in range(9, 39):
        cave[16][col] = T_WALL_STONE
    cave[4][3] = T_BIRTH
    cave[18][38] = T_EXIT_CLOSED
    return cave


def emit_common(path: Path, cave):
    lines = [
        '; generated by scripts/generate-cave1.py',
        '; Full 40x22 logical Cave 1 state. Copied into RAM by game_init.',
        f'game_cave_cols = {COLS}',
        f'game_cave_rows = {ROWS}',
        f'game_cave_bytes = {COLS * ROWS}',
        '',
        'game_cave_initial:',
    ]
    for row in cave:
        values = ', '.join(f'${value:02x}' for value in row)
        lines.append(f'    .byte {values}')
    lines.append('')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(lines), encoding='utf-8')


def emit_pce_compat(path: Path):
    # Kept as a generated file so the current Makefile interface stays stable
    # while the PCE renderer migrates to the shared runtime render buffer.
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        '; generated by scripts/generate-cave1.py\n'
        '; Runtime PCE BAT data is now produced by the shared game core.\n',
        encoding='utf-8',
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('common_output', type=Path)
    parser.add_argument('pce_output', type=Path)
    args = parser.parse_args()

    cave = build_full_cave()
    emit_common(args.common_output, cave)
    emit_pce_compat(args.pce_output)
    print(f'generated {args.common_output}')
    print(f'generated {args.pce_output}')


if __name__ == '__main__':
    main()
