#!/usr/bin/env python3
from pathlib import Path
import argparse

# Boulder Dash I constants from B1_Vars.asm
COLS = 40
ROWS = 22
VIEW_W = 32
VIEW_H = 22

T_EMPTY = 0x00
T_SOIL = 0x01
T_WALL_STONE = 0x02
T_WALL_STEEL = 0x07
T_BOULDER = 0x10
T_DIAMOND = 0x14
T_BIRTH = 0x25

# Cave 1, difficulty 0, from B1_CaveData.asm
SEED = 0x0A
START = 0x00
RND_OBJECTS = (T_EMPTY, T_BOULDER, T_DIAMOND, T_EMPTY)
RND_PROBS = (0x3C, 0x32, 0x09, 0x00)


def rnd_step(seed: int, start: int):
    # Exact 8-bit behavior of GetValPseudoRND in BoulderDashI.asm.
    p1 = 0x80 if (start & 0x02) else 0x00
    p2 = (seed >> 1) & 0x7F

    seed_sum = seed + (0x80 if (seed & 0x01) else 0x00) + 0x13
    carry = 1 if seed_sum > 0xFF else 0
    seed = seed_sum & 0xFF

    start = (start + p1 + p2 + carry) & 0xFF
    return seed, start, start


def build_full_cave():
    cave = [[T_EMPTY for _ in range(COLS)] for _ in range(ROWS)]
    seed = SEED
    start = START

    # GameCaveGetDataRND starts at row 1 and advances all 40 columns.
    # Keep all 40 RNG calls per row even though the current console viewport
    # only renders columns 0..31, otherwise later rows would diverge.
    for row in range(1, ROWS):
        for col in range(COLS):
            seed, start, value = rnd_step(seed, start)
            tile = T_SOIL
            for obj, prob in zip(RND_OBJECTS, RND_PROBS):
                if value < prob:
                    tile = obj
            cave[row][col] = tile

    # CaveFrame: steel boundary around the real 40x22 cave.
    for col in range(COLS):
        cave[0][col] = T_WALL_STEEL
        cave[ROWS - 1][col] = T_WALL_STEEL
    for row in range(ROWS):
        cave[row][0] = T_WALL_STEEL
        cave[row][COLS - 1] = T_WALL_STEEL

    # Cave 1 variable commands from B1_CaveData.asm.
    # BD1_CaveDrawLine wall stone, col 1, row 9, len 30, east.
    for col in range(1, 1 + 30):
        cave[9][col] = T_WALL_STONE

    # BD1_CaveDrawLine wall stone, col 9, row 16, len 30, east.
    for col in range(9, 9 + 30):
        cave[16][col] = T_WALL_STONE

    # Rockford birth animation start tile.
    cave[4][3] = T_BIRTH

    # Exit is at col 38,row 18 and therefore outside the current 32-col view.
    return cave


def emit_ca65(path: Path):
    cave = build_full_cave()
    lines = [
        '; generated by scripts/generate-cave1.py',
        '; Cave 1 difficulty 0: original RNG + frame + variable draw commands.',
        'game_cave_view_width = 32',
        'game_cave_view_height = 22',
        '',
        'game_cave_view:',
    ]
    for row in range(VIEW_H):
        values = ', '.join(f'${cave[row][col]:02x}' for col in range(VIEW_W))
        lines.append(f'    .byte {values}')
    lines.append('')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(lines), encoding='utf-8')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    emit_ca65(args.output)
    print(f'generated {args.output}')


if __name__ == '__main__':
    main()
