#!/usr/bin/env python3
"""Generate a ca65 autoplay stream from the headless Cave 1 solver."""

from __future__ import annotations

import importlib.util
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def load_selfplay():
    path = ROOT / "scripts" / "selfplay-regression.py"
    spec = importlib.util.spec_from_file_location("selfplay_regression", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate-rom-autoplay.py OUTPUT.inc")

    sp = load_selfplay()
    result = sp.clean_run()
    packets = sp.compress_moves(result.moves)
    out = Path(sys.argv[1])
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "; generated by scripts/generate-rom-autoplay.py",
        "; high nibble = cave-pass duration, low nibble = C64 joystick value",
        "game_autoplay_packets:",
    ]
    for offset in range(0, len(packets), 16):
        chunk = packets[offset:offset + 16]
        lines.append("    .byte " + ", ".join(f"${value:02x}" for value in chunk))
    lines += [
        "    .byte $00",
        f"game_autoplay_packet_count = {len(packets)}",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {out}: {len(packets)} packets, {result.steps} cave passes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
