#!/usr/bin/env python3
"""Generate the original Boulder Dash C64 diamond animation for SNES/PCE.

The original IRQ animation rewrites C64 character slots $48/$49/$58/$59 from
B1_MiscS.asm. B1Z_AnimTilePhaseOff selects eight phases at offsets $00..$38.
This generator extracts those exact bytes and converts each C64 multicolor
character to the same console 4bpp representation used by convert-charset.py.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

LABEL_RE = re.compile(r"^\s*T_([0-9A-Fa-f]{4})\b")
BYTE_RE = re.compile(r"\.byte\s+\$([0-9A-Fa-f]{2})", re.IGNORECASE)

FRAME_COUNT = 8
TILE_BYTES = 32
FRAME_BYTES = 4 * TILE_BYTES


def read_misc_memory(path: Path) -> dict[int, int]:
    memory: dict[int, int] = {}
    address: int | None = None

    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        label = LABEL_RE.match(line)
        if label:
            address = int(label.group(1), 16)

        value = BYTE_RE.search(line)
        if value and address is not None:
            if address in memory:
                raise SystemExit(f"{path}:{line_no}: duplicate byte at ${address:04X}")
            memory[address] = int(value.group(1), 16)
            address += 1

    return memory


def read_rows(memory: dict[int, int], address: int) -> list[int]:
    rows: list[int] = []
    for offset in range(8):
        pos = address + offset
        if pos not in memory:
            raise SystemExit(f"missing animation byte at ${pos:04X}")
        rows.append(memory[pos])
    return rows


def expand_multicolor_row(row: int) -> list[int]:
    pixels: list[int] = []
    for shift in (6, 4, 2, 0):
        value = (row >> shift) & 3
        pixels.extend((value, value))
    return pixels


def encode_4bpp(rows: list[int]) -> bytes:
    plane01 = bytearray()
    plane23 = bytearray()
    for row in rows:
        p0 = 0
        p1 = 0
        for x, value in enumerate(expand_multicolor_row(row)):
            bit = 7 - x
            if value & 1:
                p0 |= 1 << bit
            if value & 2:
                p1 |= 1 << bit
        plane01.extend((p0, p1))
        plane23.extend((0, 0))
    data = bytes(plane01 + plane23)
    assert len(data) == TILE_BYTES
    return data


def build_frames(memory: dict[int, int]) -> list[bytes]:
    frames: list[bytes] = []
    for phase in range(FRAME_COUNT):
        step = phase * 0x10
        starts = (
            0x5606 + step,  # diamond top-left  -> character $48
            0x560E + step,  # diamond top-right -> character $49
            0x5686 + step,  # diamond bot-left  -> character $58
            0x568E + step,  # diamond bot-right -> character $59
        )
        frame = b"".join(encode_4bpp(read_rows(memory, start)) for start in starts)
        assert len(frame) == FRAME_BYTES
        frames.append(frame)
    return frames


def emit(path: Path, label: str, frames: list[bytes]) -> None:
    lines = [
        "; Generated by scripts/generate-diamond-animation.py -- do not edit.",
        "; Exact 8-phase C64 diamond character animation from B1_MiscS.asm.",
        "",
    ]

    for phase, frame in enumerate(frames):
        lines.append(f"{label}_frame{phase}:")
        for offset in range(0, len(frame), 16):
            chunk = frame[offset : offset + 16]
            lines.append("    .byte " + ", ".join(f"${b:02X}" for b in chunk))
        lines.append("")

    frame_names = [f"{label}_frame{phase}" for phase in range(FRAME_COUNT)]
    lines.append(f"{label}_ptr_lo:")
    lines.append("    .byte " + ", ".join(f"<{name}" for name in frame_names))
    lines.append(f"{label}_ptr_hi:")
    lines.append("    .byte " + ", ".join(f">{name}" for name in frame_names))
    lines += [
        f"{label}_frame_count = {FRAME_COUNT}",
        f"{label}_frame_bytes = {FRAME_BYTES}",
        "",
    ]

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("snes_out", type=Path)
    parser.add_argument("pce_out", type=Path)
    args = parser.parse_args()

    frames = build_frames(read_misc_memory(args.source))
    emit(args.snes_out, "bd_diamond_anim_snes", frames)
    emit(args.pce_out, "bd_diamond_anim_pce", frames)

    print(f"generated {FRAME_COUNT} original C64 diamond animation phases")
    print(f"SNES: {args.snes_out}")
    print(f"PCE : {args.pce_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
