#!/usr/bin/env python3
from pathlib import Path
import argparse

COLS = 40
ROWS = 22
VIEW_W = 32
VIEW_H = 22

T_EMPTY = 0x00
T_SOIL = 0x01
T_WALL_STONE = 0x02
T_WALL_STEEL = 0x07
T_BOULDER = 0x10
T_DIAMOND = 0x14
T_BIRTH = 0x25

SEED = 0x0A
START = 0x00
RND_OBJECTS = (T_EMPTY, T_BOULDER, T_DIAMOND, T_EMPTY)
RND_PROBS = (0x3C, 0x32, 0x09, 0x00)


def rnd_step(seed: int, start: int):
    p1 = 0x80 if (start & 0x02) else 0x00
    p2 = (seed >> 1) & 0x7F
    seed_sum = seed + (0x80 if (seed & 0x01) else 0x00) + 0x13
    carry = 1 if seed_sum > 0xFF else 0
    seed = seed_sum & 0xFF
    start = (start + p1 + p2 + carry) & 0xFF
    return seed, start, start


def build_full_cave():
    cave = [[T_EMPTY for _ in range(COLS)] for _ in range(ROWS)]
    seed = SEED
    start = START

    for row in range(1, ROWS):
        for col in range(COLS):
            seed, start, value = rnd_step(seed, start)
            tile = T_SOIL
            for obj, prob in zip(RND_OBJECTS, RND_PROBS):
                if value < prob:
                    tile = obj
            cave[row][col] = tile

    for col in range(COLS):
        cave[0][col] = T_WALL_STEEL
        cave[ROWS - 1][col] = T_WALL_STEEL
    for row in range(ROWS):
        cave[row][0] = T_WALL_STEEL
        cave[row][COLS - 1] = T_WALL_STEEL

    for col in range(1, 31):
        cave[9][col] = T_WALL_STONE
    for col in range(9, 39):
        cave[16][col] = T_WALL_STONE
    cave[4][3] = T_BIRTH
    return cave


def emit_common(path: Path, cave):
    lines = [
        '; generated by scripts/generate-cave1.py',
        '; Cave 1 difficulty 0: original RNG + frame + variable draw commands.',
        'game_cave_view_width = 32',
        'game_cave_view_height = 22',
        '',
        'game_cave_view:',
    ]
    for row in range(VIEW_H):
        values = ', '.join(f'${cave[row][col]:02x}' for col in range(VIEW_W))
        lines.append(f'    .byte {values}')
    lines.append('')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(lines), encoding='utf-8')


def emit_pce(path: Path, cave):
    lines = [
        '; generated by scripts/generate-cave1.py',
        '; HuC6270 BAT words for the same shared 32x22 Cave 1 viewport.',
        'pce_cave_bat:',
    ]
    for row in range(VIEW_H):
        values = ', '.join(
            f'(PCE_PATTERN_TILE + ${cave[row][col]:02x})' for col in range(VIEW_W)
        )
        lines.append(f'    .word {values}')
    lines += ['', 'pce_cave_bat_bytes = 32 * 22 * 2', '']
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(lines), encoding='utf-8')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('common_output', type=Path)
    parser.add_argument('pce_output', type=Path)
    args = parser.parse_args()
    cave = build_full_cave()
    emit_common(args.common_output, cave)
    emit_pce(args.pce_output, cave)
    print(f'generated {args.common_output}')
    print(f'generated {args.pce_output}')


if __name__ == '__main__':
    main()
